# Generated by Django 5.1.15 on 2026-03-14 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFeedbackLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_link', to='lessons.lesson', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Ссылка на отзыв',
                'verbose_name_plural': 'Ссылки на отзывы',
            },
        ),
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(blank=True, max_length=200, verbose_name='Имя студента')),
                ('mentor_rating', models.PositiveSmallIntegerField(help_text='От 1 до 5', verbose_name='Оценка работы ментора')),
                ('self_activity', models.PositiveSmallIntegerField(help_text='От 1 до 5', verbose_name='Оценка своей активности')),
                ('mood', models.PositiveSmallIntegerField(help_text='От 1 до 5', verbose_name='Настроение на уроке')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('feedback_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reviews.lessonfeedbacklink', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Отзыв по уроку',
                'verbose_name_plural': 'Отзывы по урокам',
                'ordering': ['-created_at'],
            },
        ),
    ]
