# Generated by Django 5.1.15 on 2026-03-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общий балл')),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл посещаемости')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Балл заданий')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='Место в рейтинге')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Рейтинг студента',
                'verbose_name_plural': 'Рейтинги студентов',
                'ordering': ['-total_score'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
