# Generated by Django 5.1.15 on 2026-03-26 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('settings', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество месяцев курса'),
        ),
        migrations.AddField(
            model_name='payment',
            name='months_paid',
            field=models.JSONField(default=list, verbose_name='Оплаченные месяцы'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
