# Generated by Django 5.1.15 on 2026-03-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_month_count_payment_months_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('organization_type', models.CharField(choices=[('ИП', 'ИП'), ('ООО', 'ООО'), ('ОССО', 'ОССО')], default='ИП', max_length=20, verbose_name='Тип организации')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('tax_per_receipt', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Налог с каждого чека (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Данные для чека',
                'verbose_name_plural': 'Данные для чеков',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='generate_receipt',
            field=models.BooleanField(default=False, verbose_name='Сформировать чек об оплате'),
        ),
    ]
