# Generated by Django 5.1.15 on 2026-03-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_course_days_of_week'),
        ('students', '0002_alter_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение в кодкойнах')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шкала кодкойнов',
                'verbose_name_plural': 'Шкалы кодкойнов',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CoinBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_date', models.DateField(verbose_name='Дата урока')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_batches', to='courses.course', verbose_name='Курс')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Пакет начислений кодкойнов',
                'verbose_name_plural': 'Пакеты начислений кодкойнов',
                'ordering': ['-lesson_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс кодкойнов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_wallet', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Кошелек кодкойнов',
                'verbose_name_plural': 'Кошельки кодкойнов',
            },
        ),
        migrations.CreateModel(
            name='CoinWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payout_method', models.CharField(choices=[('mbank', 'МБАНК'), ('phone_balance', 'Баланс телефона')], max_length=20, verbose_name='Способ вывода')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана в')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_withdrawal_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_withdrawal_requests', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Заявка на вывод кодкойнов',
                'verbose_name_plural': 'Заявки на вывод кодкойнов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('income', 'Начисление'), ('expense', 'Списание'), ('withdrawal_request', 'Заявка на вывод'), ('withdrawal_approved', 'Вывод подтвержден'), ('withdrawal_rejected', 'Вывод отклонен'), ('correction', 'Корректировка'), ('mentor_mass_accrual', 'Массовое начисление ментором')], max_length=30, verbose_name='Тип операции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменена')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена в')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='codecoins.coinbatch', verbose_name='Пакет начислений')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='courses.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_mentor', to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='codecoins.coinwallet', verbose_name='Кошелек')),
                ('withdrawal_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='codecoins.coinwithdrawalrequest', verbose_name='Заявка на вывод')),
            ],
            options={
                'verbose_name': 'Транзакция кодкойнов',
                'verbose_name_plural': 'Транзакции кодкойнов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinWithdrawalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_open', models.BooleanField(default=False, verbose_name='Вывод открыт')),
                ('next_open_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующее открытие')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_withdrawal_settings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Настройка вывода кодкойнов',
                'verbose_name_plural': 'Настройки вывода кодкойнов',
            },
        ),
        migrations.CreateModel(
            name='CoinBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='codecoins.coinbatch', verbose_name='Пакет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_batch_items', to='students.student', verbose_name='Студент')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='codecoins.coinscale', verbose_name='Шкала')),
            ],
            options={
                'verbose_name': 'Элемент начисления кодкойнов',
                'verbose_name_plural': 'Элементы начисления кодкойнов',
                'ordering': ['batch', 'student__full_name'],
                'unique_together': {('batch', 'student', 'scale')},
            },
        ),
    ]
