# Generated by Django 4.2.7 on 2026-03-18 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина замены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_substitutions', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='lessons.lesson', verbose_name='Урок')),
                ('original_mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_original', to=settings.AUTH_USER_MODEL, verbose_name='Основной ментор')),
                ('substitute_mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_substitute', to=settings.AUTH_USER_MODEL, verbose_name='Заменяющий ментор')),
            ],
            options={
                'verbose_name': 'Замена ментора',
                'verbose_name_plural': 'Замены менторов',
                'ordering': ['-lesson__lesson_date', '-lesson__start_time'],
                'unique_together': {('lesson', 'original_mentor', 'substitute_mentor')},
            },
        ),
        migrations.CreateModel(
            name='SubstituteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_mark_attendance', models.BooleanField(default=True, verbose_name='Может отмечать посещаемость')),
                ('can_create_materials', models.BooleanField(default=True, verbose_name='Может создавать материалы')),
                ('can_view_grades', models.BooleanField(default=True, verbose_name='Может просматривать оценки')),
                ('can_create_assignments', models.BooleanField(default=True, verbose_name='Может создавать задания')),
                ('can_grade_assignments', models.BooleanField(default=False, verbose_name='Может оценивать задания')),
                ('substitution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='lessons.mentorsubstitution', verbose_name='Замена')),
            ],
            options={
                'verbose_name': 'Права доступа замены',
                'verbose_name_plural': 'Права доступа замен',
            },
        ),
    ]
