# Generated by Django 4.2.7 on 2026-03-19 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_course_days_of_week'),
        ('lessons', '0002_mentorsubstitution_substituteaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_substitutions', to='courses.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_substitution', to='lessons.lesson', verbose_name='Урок')),
                ('original_mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='completed_substitutions_as_original', to=settings.AUTH_USER_MODEL, verbose_name='Основной ментор')),
                ('substitute_mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='completed_substitutions', to=settings.AUTH_USER_MODEL, verbose_name='Заменяющий ментор')),
            ],
            options={
                'verbose_name': 'Проведенная замена',
                'verbose_name_plural': 'Проведенные замены',
                'unique_together': {('substitute_mentor', 'course', 'lesson')},
            },
        ),
    ]
