# Generated by Django 4.2.7 on 2026-03-19 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0003_completedsubstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='temporary_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporarily_mentoring_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Временный ментор (замена)'),
        ),
    ]
