[build]
builder = "RAILPACK"

[deploy]
startCommand = "cd crm_lms && python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py shell -c \"from django.contrib.auth import get_user_model; User=get_user_model(); u=User.objects.filter(username='Ramir').first(); print('exists' if u else User.objects.create_superuser(username='Ramir', password='codify123'))\" && python manage.py runserver 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
