# Generated by Django 5.1.15 on 2026-03-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Предмет/Направление')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('active', 'Активный'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='planned', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('duration_months', models.PositiveSmallIntegerField(default=3, verbose_name='Длительность (мес.)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Кабинет')),
                ('format', models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн'), ('hybrid', 'Гибрид')], default='offline', max_length=10, verbose_name='Формат')),
                ('days_of_week', models.CharField(choices=[('mon_wed_fri', 'Пн/Ср/Пт'), ('tue_thu_sat', 'Вт/Чт/Сб'), ('mon_to_fri', 'Пн-Пт'), ('sat_sun', 'Сб/Вс'), ('custom', 'Другое')], default='mon_wed_fri', max_length=20, verbose_name='Дни занятий')),
                ('lesson_start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('lesson_end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('capacity', models.PositiveSmallIntegerField(default=15, verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('color', models.CharField(default='#7c3aed', max_length=7, verbose_name='Цвет (HEX)')),
                ('assistant_mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_courses', to=settings.AUTH_USER_MODEL, verbose_name='Помощник ментора')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_courses', to=settings.AUTH_USER_MODEL, verbose_name='Ментор')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateField(blank=True, null=True, verbose_name='Дата зачисления')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='Дата выбытия')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('left', 'Выбыл'), ('frozen', 'Заморожен'), ('graduated', 'Окончил')], default='active', max_length=20, verbose_name='Статус')),
                ('invited_to_account', models.BooleanField(default=False, verbose_name='Приглашён в аккаунт')),
                ('account_registered', models.BooleanField(default=False, verbose_name='Аккаунт зарегистрирован')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Прогресс (%)')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Рейтинг')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_students', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студент курса',
                'verbose_name_plural': 'Студенты курса',
                'ordering': ['student__full_name'],
                'unique_together': {('course', 'student')},
            },
        ),
    ]
