# Generated by Django 5.1.15 on 2026-03-14 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='Бесконечный курс'),
        ),
        migrations.CreateModel(
            name='TicketBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_tickets', models.PositiveIntegerField(default=0, verbose_name='Всего талонов')),
                ('used_tickets', models.PositiveIntegerField(default=0, verbose_name='Использовано талонов')),
                ('total_attended_lessons', models.PositiveIntegerField(default=0, verbose_name='Всего посещено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_balance', to='courses.coursestudent', verbose_name='Запись на курс')),
            ],
            options={
                'verbose_name': 'Баланс талонов',
                'verbose_name_plural': 'Балансы талонов',
            },
        ),
        migrations.CreateModel(
            name='TicketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('add', 'Начисление'), ('consume', 'Списание'), ('adjust', 'Корректировка'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price_per_ticket', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость талона')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Общая сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('lesson_date', models.DateField(blank=True, null=True, verbose_name='Дата занятия')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_transactions', to='courses.coursestudent', verbose_name='Запись на курс')),
            ],
            options={
                'verbose_name': 'Операция с талонами',
                'verbose_name_plural': 'Операции с талонами',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_date', models.DateField(verbose_name='Дата занятия')),
                ('lessons_count', models.PositiveIntegerField(default=1, verbose_name='Количество занятий')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attendances', to='courses.coursestudent', verbose_name='Запись на курс')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отметил')),
            ],
            options={
                'verbose_name': 'Посещение по талонам',
                'verbose_name_plural': 'Посещения по талонам',
                'ordering': ['-lesson_date'],
                'unique_together': {('enrollment', 'lesson_date')},
            },
        ),
    ]
