# Generated by Django 5.1.15 on 2026-03-15 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_unlimited_ticketbalance_tickettransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция талонов', 'verbose_name_plural': 'Транзакции талонов'},
        ),
        migrations.AlterUniqueTogether(
            name='ticketattendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ticketbalance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ticketbalance',
            name='total_attended_lessons',
        ),
        migrations.RemoveField(
            model_name='tickettransaction',
            name='lesson_date',
        ),
        migrations.RemoveField(
            model_name='tickettransaction',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='tickettransaction',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='tickettransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tickettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('add', 'Добавление'), ('consume', 'Списание'), ('adjust', 'Корректировка')], default='add', max_length=10, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='ticketattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='ticketattendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attendances', to='courses.coursestudent', verbose_name='Зачисление'),
        ),
        migrations.AlterField(
            model_name='ticketbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='ticketbalance',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_balance', to='courses.coursestudent', verbose_name='Зачисление'),
        ),
        migrations.AlterField(
            model_name='ticketbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_transactions', to='courses.coursestudent', verbose_name='Зачисление'),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='price_per_ticket',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена за талон'),
        ),
        migrations.RemoveField(
            model_name='ticketattendance',
            name='updated_at',
        ),
    ]
