# Generated by Django 5.1.15 on 2026-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_tickettransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=models.JSONField(default=list, verbose_name='Дни недели'),
        ),
    ]
