# Generated by Django 5.1.15 on 2026-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chat_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на чат'),
        ),
        migrations.AddField(
            model_name='course',
            name='online_lesson_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на онлайн урок'),
        ),
    ]
