# Generated by Django 6.0.3 on 2026-03-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_chat_link_course_online_lesson_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='assistant_mentor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='course',
            name='chat_link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='color',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='format',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_unlimited',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson_end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson_start_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='online_lesson_link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='room',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('left', 'Выбыл'), ('frozen', 'Заморожен'), ('graduated', 'Окончил'), ('expelled', 'Отчислен')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
