# Generated by Django 6.0.3 on 2026-03-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options_remove_course_assistant_mentor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assistant_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_courses', to=settings.AUTH_USER_MODEL, verbose_name='Помощник ментора'),
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='course',
            name='chat_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на чат'),
        ),
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#7c3aed', max_length=7, verbose_name='Цвет (HEX)'),
        ),
        migrations.AddField(
            model_name='course',
            name='days_of_week',
            field=models.JSONField(default=list, verbose_name='Дни недели'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Длительность (мес.)'),
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн'), ('hybrid', 'Гибрид')], default='offline', max_length=10, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='Бесконечный курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_courses', to=settings.AUTH_USER_MODEL, verbose_name='Ментор'),
        ),
        migrations.AddField(
            model_name='course',
            name='online_lesson_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на онлайн урок'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('active', 'Активный'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Предмет/Направление'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Новый курс', max_length=200, verbose_name='Название'),
        ),
    ]
