# Generated by Django 6.0.3 on 2026-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_assistant_mentor_course_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ставка за час работы для почасовой оплаты', max_digits=10, verbose_name='Почасовая ставка ментора'),
        ),
        migrations.AddField(
            model_name='course',
            name='salary_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Процент от суммы оплат студентов за курс', max_digits=5, verbose_name='Процент от оплат'),
        ),
        migrations.AddField(
            model_name='course',
            name='salary_type',
            field=models.CharField(choices=[('hourly', 'Почасовая'), ('monthly', 'Фиксированная'), ('percentage', 'Процент от оплат'), ('course', 'За курс')], default='monthly', max_length=10, verbose_name='Тип оплаты'),
        ),
    ]
