# Generated by Django migration system

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_tickettariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тарифа')),
                ('lessons_count', models.PositiveIntegerField(verbose_name='Количество талонов')),
                ('price_per_lesson', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за талон')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Тариф талонов',
                'verbose_name_plural': 'Тарифы талонов',
                'ordering': ['-created_at'],
            },
        ),
    ]
