# Generated by Django 6.0.3 on 2026-04-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_tickettariff'),
        ('organizations', '0005_remove_organization_payment_per_lesson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettariff',
            options={'ordering': ['lessons_count'], 'verbose_name': 'Тариф талонов', 'verbose_name_plural': 'Тарифы талонов'},
        ),
        migrations.AddField(
            model_name='tickettariff',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='tickettariff',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='tickettariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tickettariff',
            name='lessons_count',
            field=models.PositiveIntegerField(verbose_name='Количество занятий'),
        ),
        migrations.AlterField(
            model_name='tickettariff',
            name='price_per_lesson',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за занятие'),
        ),
        migrations.AlterField(
            model_name='tickettariff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
