# Generated by Django 5.1.15 on 2026-03-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffInvitation',
        ),
    ]
