# Generated by Django 6.0.3 on 2026-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='ОкууTrack', max_length=200, verbose_name='Заголовок футера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact_info', models.TextField(blank=True, verbose_name='Контактная информация')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text="JSON формат: {'telegram': 'url', 'instagram': 'url'}", verbose_name='Социальные сети')),
                ('additional_links', models.JSONField(blank=True, default=dict, help_text="JSON формат: {'Название': 'url'}", verbose_name='Дополнительные ссылки')),
                ('copyright_text', models.CharField(default='© 2024 ОкууTrack. Все права защищены.', max_length=500, verbose_name='Текст копирайта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Контент футера',
                'verbose_name_plural': 'Контент футера',
            },
        ),
    ]
