# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_footercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='public_offer',
            field=models.TextField(blank=True, verbose_name="Публичная оферта"),
        ),
    ]
