# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_footercontent_public_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL идентификатор')),
                ('title', models.CharField(max_length=200, verbose_name='Название ссылки')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Навигационная ссылка футера',
                'verbose_name_plural': 'Навигационные ссылки футера',
                'ordering': ['order', 'title'],
            },
        ),
    ]
