# Generated by Django 4.2.7 on 2026-03-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
            ],
            options={
                'verbose_name': 'Неудачная попытка входа',
                'verbose_name_plural': 'Неудачные попытки входа',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Время блокировки')),
                ('lock_reason', models.CharField(default='Too many failed login attempts', max_length=255, verbose_name='Причина блокировки')),
                ('unlock_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Токен разблокировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_lock', to='accounts.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Блокировка аккаунта',
                'verbose_name_plural': 'Блокировки аккаунтов',
            },
        ),
    ]
