# Generated by Django 5.1.15 on 2026-03-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountlock',
            name='user',
        ),
        migrations.DeleteModel(
            name='FailedLoginAttempt',
        ),
        migrations.DeleteModel(
            name='AccountLock',
        ),
    ]
