# Generated by Django 6.0.3 on 2026-04-01 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_accountlock_user_delete_failedloginattempt_and_more'),
        ('organizations', '0003_alter_organizationmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('view', 'Просмотр'), ('export', 'Экспорт'), ('import', 'Импорт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип действия')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Представление объекта')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История действий',
                'verbose_name_plural': 'История действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_action_user_id_293475_idx'), models.Index(fields=['action_type', 'created_at'], name='core_action_action__9d68ee_idx'), models.Index(fields=['organization', 'created_at'], name='core_action_organiz_708514_idx')],
            },
        ),
    ]
