# Generated by Django 5.1.15 on 2026-03-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lectures', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('max_score', models.PositiveSmallIntegerField(default=100, verbose_name='Макс. балл')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимое')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='Курс')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lectures.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ текстом')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Файл ответа')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('not_submitted', 'Не сдано'), ('submitted', 'Сдано'), ('checked', 'Проверено'), ('revision', 'На доработке')], default='not_submitted', max_length=20, verbose_name='Статус')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на задание',
                'verbose_name_plural': 'Ответы на задания',
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_grades', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assignments.assignmentsubmission', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
