# Generated by Django 5.1.15 on 2026-03-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('quizzes', '0002_quiz_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='quizzes.quiz', verbose_name='Связанный тест'),
        ),
    ]
