# Generated by Django 6.0.3 on 2026-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentgrade',
            name='ai_confidence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уверенность ИИ (%)'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='ai_feedback',
            field=models.JSONField(blank=True, null=True, verbose_name='AI обратная связь'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='ai_graded',
            field=models.BooleanField(default=False, verbose_name='Проверено ИИ'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='ai_strengths',
            field=models.TextField(blank=True, verbose_name='Сильные стороны (ИИ)'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='ai_suggestions',
            field=models.TextField(blank=True, verbose_name='Рекомендации (ИИ)'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='ai_weaknesses',
            field=models.TextField(blank=True, verbose_name='Слабые стороны (ИИ)'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='plagiarism_reason',
            field=models.TextField(blank=True, verbose_name='Причина подозрения'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='plagiarism_suspicious',
            field=models.BooleanField(default=False, verbose_name='Подозрение на плагиат'),
        ),
    ]
