# Generated by Django 6.0.3 on 2026-04-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_block_after_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='block_after_deadline',
        ),
    ]
