# Generated by Django 5.1.15 on 2026-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_organization'),
        ('debts', '0001_initial'),
        ('students', '0003_student_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='month',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='debt',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, verbose_name='Год'),
        ),
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together={('student', 'course', 'month', 'year')},
        ),
    ]
