# Generated by Django 6.0.3 on 2026-04-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_month_debt_year_alter_debt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_type',
            field=models.CharField(choices=[('monthly', 'Месячный'), ('lesson', 'Занятие')], default='monthly', max_length=15, verbose_name='Тип долга'),
        ),
    ]
