# Generated by Django 6.0.3 on 2026-04-01 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('organizations', '0003_alter_organizationmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='audience',
            field=models.CharField(choices=[('all', 'Все'), ('admins', 'Администраторы'), ('mentors', 'Менторы'), ('students', 'Студенты')], default='all', max_length=10, verbose_name='Аудитория'),
        ),
    ]
