# Generated by Django 6.0.3 on 2026-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_per_lesson',
            field=models.BooleanField(default=False, help_text='Если включено, то оплата за учебу отключается и все курсы становятся бесконечными', verbose_name='Переход на оплату по занятиям'),
        ),
    ]
