# Generated by Django 6.0.3 on 2026-04-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_payment_per_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='payment_per_lesson',
        ),
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(default='0084', help_text='Код в формате 0084', max_length=10, verbose_name='Код филиала'),
        ),
    ]
