# Generated by Django 6.0.3 on 2026-04-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID сообщения в Telegram'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('review', 'Отзыв'), ('idea', 'Идея'), ('bug', 'Баг'), ('complaint', 'Жалоба'), ('suggestion', 'Предложение')], max_length=20, verbose_name='Тип обратной связи'),
        ),
    ]
