# Generated by Django 5.1.15 on 2026-03-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_change_language_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Супер-Администратор'), ('admin', 'Администратор'), ('mentor', 'Ментор'), ('staff', 'Персонал'), ('student', 'Студент')], default='admin', max_length=20, verbose_name='Роль'),
        ),
    ]
