# Generated by Django 5.1.15 on 2026-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_last_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seed для аватара'),
        ),
    ]
