# Generated by Django 5.1.15 on 2026-03-25 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_populate_avatar_seeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Seed для аватара'),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название аккаунта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Связанный аккаунт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Основной пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт пользователя',
                'verbose_name_plural': 'Аккаунты пользователей',
                'ordering': ['-last_used', '-created_at'],
                'unique_together': {('user', 'account_user')},
            },
        ),
    ]
