# Generated by Django 6.0.3 on 2026-04-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('attendance', '0002_attendancerecord_marked_by'),
    ]

    operations = [
    ]
