# Generated by Django 6.0.3 on 2026-03-29 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('organizations', '0003_alter_organizationmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeaccount',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='financecategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transactions', to='organizations.organization', verbose_name='Организация'),
        ),
    ]
