# Generated by Django 6.0.3 on 2026-03-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financeaccount_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='Автоматически созданная'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='related_entity_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанной сущности'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='related_entity_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип связанной сущности'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='transfer_to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from_transactions', to='finance.financeaccount', verbose_name='Счёт получения (для переводов)'),
        ),
    ]
