# Generated by Django 6.0.3 on 2026-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financetransaction_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Филиал'),
        ),
    ]
