# Generated by Django 5.1.15 on 2026-03-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Короткое имя')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('salary_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('percent', 'Процент'), ('mixed', 'Смешанная')], default='fixed', max_length=10, verbose_name='Тип зарплаты')),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фиксированная зарплата')),
                ('percent_salary', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент от оплат')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль ментора',
                'verbose_name_plural': 'Профили менторов',
            },
        ),
    ]
