# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        # Обновляем choices для salary_type
        migrations.AlterField(
            model_name='mentorprofile',
            name='salary_type',
            field=models.CharField(
                choices=[
                    ('fixed', 'Фиксированная'), 
                    ('hourly', 'Почасовая'), 
                    ('percent', 'Процент'), 
                    ('mixed', 'Смешанная')
                ],
                default='fixed',
                max_length=10,
                verbose_name='Тип зарплаты'
            ),
        ),
        # Добавляем поле hourly_rate
        migrations.AddField(
            model_name='mentorprofile',
            name='hourly_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name='Ставка за час'
            ),
        ),
        # Добавляем поля 2FA
        migrations.AddField(
            model_name='mentorprofile',
            name='two_factor_enabled',
            field=models.BooleanField(
                default=False,
                verbose_name='Двухфакторная аутентификация'
            ),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='two_factor_code',
            field=models.CharField(
                blank=True,
                max_length=6,
                verbose_name='Код 2FA'
            ),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='two_factor_code_expires',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Срок действия кода'
            ),
        ),
    ]
