# Generated by Django 5.1.15 on 2026-03-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_add_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='two_factor_code',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='two_factor_code_expires',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='two_factor_enabled',
        ),
    ]
