# Generated by Django 4.2.7 on 2026-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_remove_mentorprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='kpi',
            field=models.FloatField(blank=True, null=True, verbose_name='KPI'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='kpi_status',
            field=models.CharField(blank=True, choices=[('recommended', 'Рекомендуется'), ('good', 'Хорошо'), ('caution', 'С осторожностью'), ('not_recommended', 'Не рекомендуется')], max_length=20, null=True, verbose_name='KPI статус'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='kpi_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KPI обновлён'),
        ),
    ]
