# Generated by Django 5.1.15 on 2026-03-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_mentorprofile_kpi_mentorprofile_kpi_status_and_more'),
        ('organizations', '0002_alter_organizationmember_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация'),
        ),
    ]
