# Generated by Django 5.1.15 on 2026-03-13 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('source', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('referral', 'Реферал'), ('website', 'Сайт'), ('vk', 'ВКонтакте'), ('other', 'Другое')], max_length=20, verbose_name='Источник')),
                ('channel', models.CharField(blank=True, max_length=100, verbose_name='Канал')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('consultation', 'Консультация'), ('trial_lesson', 'Пробный урок'), ('no_show', 'Не пришёл'), ('enrolling', 'Зачисление'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.course', verbose_name='Интересующий курс')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='leads.lead', verbose_name='Лид')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
            ],
            options={
                'verbose_name': 'Действие с лидом',
                'verbose_name_plural': 'Действия с лидами',
                'ordering': ['-created_at'],
            },
        ),
    ]
