# Generated by Django 5.1.15 on 2026-03-17 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Дубликат')),
            ],
            options={
                'verbose_name': 'Отправка формы',
                'verbose_name_plural': 'Отправки форм',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название формы')),
                ('channel', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('website', 'Сайт'), ('other', 'Другое')], max_length=20, verbose_name='Канал')),
                ('header', models.CharField(max_length=300, verbose_name='Заголовок формы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('button_text', models.CharField(default='Отправить', max_length=50, verbose_name='Текст кнопки')),
                ('success_text', models.TextField(verbose_name='Текст после отправки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Форма активна')),
                ('prevent_duplicates', models.BooleanField(default=True, verbose_name='Защита от дублей')),
                ('auto_create_lead', models.BooleanField(default=True, verbose_name='Автосоздание лида')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Уникальный ID')),
            ],
            options={
                'verbose_name': 'Форма лида',
                'verbose_name_plural': 'Формы лидов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('referral', 'Реферал'), ('website', 'Сайт'), ('vk', 'ВКонтакте'), ('other', 'Другое'), ('form', 'Форма')], max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='lead',
            name='form_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.formsubmission', verbose_name='Отправка формы'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leads.leadform', verbose_name='Форма'),
        ),
        migrations.CreateModel(
            name='LeadFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(choices=[('first_name', 'Имя'), ('last_name', 'Фамилия'), ('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('age', 'Возраст'), ('city', 'Город'), ('course', 'Курс/направление'), ('comment', 'Комментарий'), ('birth_date', 'Дата рождения')], max_length=20, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('tel', 'Телефон'), ('email', 'Email'), ('number', 'Число'), ('date', 'Дата'), ('textarea', 'Текстовая область'), ('select', 'Выбор')], default='text', max_length=20, verbose_name='Тип поля')),
                ('label', models.CharField(max_length=100, verbose_name='Label поля')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Placeholder')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('mask', models.CharField(blank=True, max_length=50, verbose_name='Маска')),
                ('options', models.TextField(blank=True, help_text='Опции для select поля (каждая с новой строки)', verbose_name='Опции')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='leads.leadform', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля формы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(verbose_name='Значение')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='leads.formsubmission', verbose_name='Отправка')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leadformfield', verbose_name='Поле')),
            ],
            options={
                'verbose_name': 'Значение поля',
                'verbose_name_plural': 'Значения полей',
                'unique_together': {('submission', 'field')},
            },
        ),
    ]
