# Generated by Django 5.1.15 on 2026-03-17 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_formsubmission_leadform_alter_lead_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadGenerationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название формы')),
                ('channel', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('website', 'Website'), ('other', 'Другое')], max_length=20, verbose_name='Канал')),
                ('header', models.CharField(max_length=300, verbose_name='Заголовок формы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('button_text', models.CharField(default='Отправить', max_length=100, verbose_name='Текст кнопки')),
                ('success_text', models.TextField(default='Спасибо за заявку!', verbose_name='Текст после отправки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('prevent_duplicates', models.BooleanField(default=True, verbose_name='Защита от дублей')),
                ('auto_create_lead', models.BooleanField(default=True, verbose_name='Автосоздание лида')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Форма лидогенерации',
                'verbose_name_plural': 'Формы лидогенерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='formfieldvalue',
            options={'verbose_name': 'Значение поля формы', 'verbose_name_plural': 'Значения полей формы'},
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leads.leadgenerationform', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='leadformfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='leads.leadgenerationform', verbose_name='Форма'),
        ),
        migrations.DeleteModel(
            name='LeadForm',
        ),
    ]
