# Generated by Django 5.1.15 on 2026-03-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leadgenerationform_alter_formfieldvalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название источника')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='lead_source_icons/', verbose_name='Иконка')),
                ('is_default', models.BooleanField(default=False, verbose_name='Источник по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Источник лида',
                'verbose_name_plural': 'Источники лидов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='lead_status_icons/', verbose_name='Иконка')),
                ('is_default', models.BooleanField(default=False, verbose_name='Статус по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус лида',
                'verbose_name_plural': 'Статусы лидов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('referral', 'Реферал'), ('website', 'Сайт'), ('vk', 'ВКонтакте'), ('other', 'Другое'), ('form', 'Форма')], max_length=20, verbose_name='Источник (старый вариант)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('consultation', 'Консультация'), ('trial_lesson', 'Пробный урок'), ('no_show', 'Не пришёл'), ('enrolling', 'Зачисление'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус (старый вариант)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadstatus', verbose_name='Статус'),
        ),
    ]
