# Generated by Django 5.1.15 on 2026-03-18 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadsource_leadstatus_alter_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadgenerationform',
            name='default_status',
            field=models.ForeignKey(blank=True, help_text='Статус, который будет присвоен лидам из этой формы', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadstatus', verbose_name='Статус лида по умолчанию'),
        ),
    ]
