# Generated by Django 5.1.15 on 2026-03-23 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadgenerationform_default_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('name', 'Имя'), ('full_name', 'Полное имя'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Тип совпадения')),
                ('match_value', models.CharField(max_length=255, verbose_name='Значение совпадения')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержденные дубли')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Обработано')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Группа дубликатов',
                'verbose_name_plural': 'Группы дубликатов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='lead',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='lead',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.CreateModel(
            name='LeadMergeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merge_reason', models.TextField(verbose_name='Причина объединения')),
                ('fields_merged', models.JSONField(default=dict, verbose_name='Объединенные поля')),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто объединил')),
                ('merged_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_merged', to='leads.lead', verbose_name='Объединенный лид')),
                ('primary_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_primary', to='leads.lead', verbose_name='Основной лид')),
            ],
            options={
                'verbose_name': 'История объединения',
                'verbose_name_plural': 'Истории объединений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(verbose_name='Дата отчета')),
                ('total_leads', models.IntegerField(default=0, verbose_name='Всего лидов')),
                ('new_leads', models.IntegerField(default=0, verbose_name='Новых лидов')),
                ('converted_leads', models.IntegerField(default=0, verbose_name='Конвертировано')),
                ('lost_leads', models.IntegerField(default=0, verbose_name='Потеряно')),
                ('conversion_rate', models.FloatField(default=0.0, verbose_name='Конверсия %')),
                ('avg_processing_time', models.FloatField(default=0.0, verbose_name='Среднее время обработки (часы)')),
            ],
            options={
                'verbose_name': 'Снепшот отчета',
                'verbose_name_plural': 'Снепшоты отчетов',
                'ordering': ['-report_date'],
                'unique_together': {('report_date',)},
            },
        ),
        migrations.CreateModel(
            name='LeadActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Редактирование'), ('status_change', 'Смена статуса'), ('assign', 'Назначение менеджера'), ('comment', 'Добавление комментария'), ('merge', 'Объединение'), ('archive', 'Архивирование'), ('delete', 'Удаление'), ('convert_to_student', 'Конвертация в студента'), ('import', 'Импорт')], max_length=20, verbose_name='Тип действия')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='Название поля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='leads.lead', verbose_name='Лид')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='leads_leada_lead_id_d2e201_idx'), models.Index(fields=['performed_by', '-created_at'], name='leads_leada_perform_cdf180_idx'), models.Index(fields=['action_type', '-created_at'], name='leads_leada_action__59115d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной лид')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Уверенность в дубликате')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_records', to='leads.lead', verbose_name='Лид')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='leads.leadduplicategroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Дубликат лида',
                'verbose_name_plural': 'Дубликаты лидов',
                'ordering': ['-confidence_score'],
                'unique_together': {('group', 'lead')},
            },
        ),
    ]
