# Generated by Django 5.1.15 on 2026-03-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('graduated', 'Окончил'), ('expelled', 'Отчислен'), ('left', 'Ушедший')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
