# Generated by Django 6.0.3 on 2026-03-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentnote'),
        ('students', '0003_student_organization'),
    ]

    operations = [
    ]
