# Generated by Django 6.0.3 on 2026-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_merge_0002_studentnote_0003_student_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
