# Generated by Django 6.0.3 on 2026-04-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentnote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='student',
            name='email_notifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Email уведомления'),
        ),
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызский'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык интерфейса'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='student',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
