# Generated by Django 6.0.3 on 2026-04-03 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_bio_student_email_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Заметка администратора',
                'verbose_name_plural': 'Заметки администраторов',
                'ordering': ['-created_at'],
            },
        ),
    ]
